### ISSUE TITLE
建议：添加几种特殊生物的的Helper

### ISSUE THREAD

**Issue by haiman233** [ybw0014/GuizhanLib#29]
羊：16种颜色
鹦鹉：几种颜色
羊驼/行商羊驼：几种颜色
蘑菇牛：红蘑菇牛和棕蘑菇牛
史莱姆、岩浆怪、幻翼：体型大小 （幻翼是有Size标签的）
僵尸：小僵尸/可破坏门僵尸
僵尸村民：所有职业
骷髅马/僵尸马：骷髅马和骷髅陷阱马/驯服状态
蜜蜂：携带花粉/蜇过玩家或生物
热带鱼：品种
蝙蝠：普通和倒挂
豹猫/狼：驯服/项圈颜色
美西螈：三种颜色
青蛙：三种颜色
山羊：普通山羊、尖叫山羊、独角山羊（左侧角/右侧角）

**Comment by ybw0014** [comment]
羊毛颜色已经有了，村民职业也已经有了。
除非有需求（这些Helper大部分都只有MobCapturer用到），不然我是不会加的。
