### ISSUE TITLE
UpdaterTask.getRepoInfo() 可能产生未捕获的异常

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [ybw0014/GuizhanLib#37]
### 问题描述
无法连接到构建站（比如，断网的本地服务器）时，getRepoInfo() 会 fetch(URL) 失败。

虽然 fetch(URL) 有所准备，但返回的 null 会导致 JsonUtil.parse(String) 生成 IllegalArgumentException。

该异常没有得到妥善处理，因而会产生错误信息。

代码水平不高的服主可能会误以为利用 GuizhzanLib 实现自动更新的插件存在重要漏洞，导致漏洞误报。
### 复现步骤
1. 将服务器断网；
2. 将该插件，以及需要该插件来自动更新的插件（如：神秘科技汉化版）放入插件文件夹；
3. 运行服务端软件。

此时，除了“无法从构建站获取更新信息”之类的提示信息外，还会输出未捕获的异常。
### 服务端软件
Spigot

**Comment by ybw0014** [comment]
目前堆栈信息确实会输出，后面会考虑隐藏。
